/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EnrollStudentCommand,
  EnrollmentDto,
  GetApiEnrollmentsParams,
  UpdateEnrollmentSectionCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiEnrollments = (
    enrollStudentCommand: EnrollStudentCommand,
 signal?: AbortSignal
) => {


      return customInstance<number | string>(
      {url: `/api/Enrollments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enrollStudentCommand, signal
    },
      );
    }



export const getPostApiEnrollmentsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEnrollments>>, TError,{data: EnrollStudentCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiEnrollments>>, TError,{data: EnrollStudentCommand}, TContext> => {

const mutationKey = ['postApiEnrollments'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEnrollments>>, {data: EnrollStudentCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiEnrollments(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiEnrollmentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEnrollments>>>
    export type PostApiEnrollmentsMutationBody = EnrollStudentCommand
    export type PostApiEnrollmentsMutationError = unknown

    export const usePostApiEnrollments = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEnrollments>>, TError,{data: EnrollStudentCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiEnrollments>>,
        TError,
        {data: EnrollStudentCommand},
        TContext
      > => {
      return useMutation(getPostApiEnrollmentsMutationOptions(options), queryClient);
    }
    export const getApiEnrollments = (
    params?: GetApiEnrollmentsParams,
 signal?: AbortSignal
) => {


      return customInstance<EnrollmentDto[]>(
      {url: `/api/Enrollments`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiEnrollmentsQueryKey = (params?: GetApiEnrollmentsParams,) => {
    return [
    `/api/Enrollments`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiEnrollmentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiEnrollments>>, TError = unknown>(params?: GetApiEnrollmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEnrollmentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEnrollments>>> = ({ signal }) => getApiEnrollments(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEnrollmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEnrollments>>>
export type GetApiEnrollmentsQueryError = unknown


export function useGetApiEnrollments<TData = Awaited<ReturnType<typeof getApiEnrollments>>, TError = unknown>(
 params: undefined |  GetApiEnrollmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnrollments>>,
          TError,
          Awaited<ReturnType<typeof getApiEnrollments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnrollments<TData = Awaited<ReturnType<typeof getApiEnrollments>>, TError = unknown>(
 params?: GetApiEnrollmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnrollments>>,
          TError,
          Awaited<ReturnType<typeof getApiEnrollments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnrollments<TData = Awaited<ReturnType<typeof getApiEnrollments>>, TError = unknown>(
 params?: GetApiEnrollmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEnrollments<TData = Awaited<ReturnType<typeof getApiEnrollments>>, TError = unknown>(
 params?: GetApiEnrollmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollments>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEnrollmentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const putApiEnrollmentsIdSection = (
    id: number | string,
    updateEnrollmentSectionCommand: UpdateEnrollmentSectionCommand,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Enrollments/${id}/section`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateEnrollmentSectionCommand, signal
    },
      );
    }



export const getPutApiEnrollmentsIdSectionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiEnrollmentsIdSection>>, TError,{id: number | string;data: UpdateEnrollmentSectionCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiEnrollmentsIdSection>>, TError,{id: number | string;data: UpdateEnrollmentSectionCommand}, TContext> => {

const mutationKey = ['putApiEnrollmentsIdSection'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiEnrollmentsIdSection>>, {id: number | string;data: UpdateEnrollmentSectionCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiEnrollmentsIdSection(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiEnrollmentsIdSectionMutationResult = NonNullable<Awaited<ReturnType<typeof putApiEnrollmentsIdSection>>>
    export type PutApiEnrollmentsIdSectionMutationBody = UpdateEnrollmentSectionCommand
    export type PutApiEnrollmentsIdSectionMutationError = unknown

    export const usePutApiEnrollmentsIdSection = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiEnrollmentsIdSection>>, TError,{id: number | string;data: UpdateEnrollmentSectionCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiEnrollmentsIdSection>>,
        TError,
        {id: number | string;data: UpdateEnrollmentSectionCommand},
        TContext
      > => {
      return useMutation(getPutApiEnrollmentsIdSectionMutationOptions(options), queryClient);
    }
    export const deleteApiEnrollmentsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Enrollments/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiEnrollmentsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnrollmentsId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnrollmentsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiEnrollmentsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiEnrollmentsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiEnrollmentsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiEnrollmentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiEnrollmentsId>>>

    export type DeleteApiEnrollmentsIdMutationError = unknown

    export const useDeleteApiEnrollmentsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnrollmentsId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiEnrollmentsId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiEnrollmentsIdMutationOptions(options), queryClient);
    }
    export const getApiEnrollmentsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<EnrollmentDto>(
      {url: `/api/Enrollments/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiEnrollmentsIdQueryKey = (id: number | string,) => {
    return [
    `/api/Enrollments/${id}`
    ] as const;
    }


export const getGetApiEnrollmentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEnrollmentsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEnrollmentsId>>> = ({ signal }) => getApiEnrollmentsId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEnrollmentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEnrollmentsId>>>
export type GetApiEnrollmentsIdQueryError = unknown


export function useGetApiEnrollmentsId<TData = Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnrollmentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiEnrollmentsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnrollmentsId<TData = Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnrollmentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiEnrollmentsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnrollmentsId<TData = Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEnrollmentsId<TData = Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnrollmentsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEnrollmentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






