/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiSessionsParams,
  OpenSessionCommand,
  SessionDto
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiSessions = (
    openSessionCommand: OpenSessionCommand,
 signal?: AbortSignal
) => {


      return customInstance<number | string>(
      {url: `/api/Sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: openSessionCommand, signal
    },
      );
    }



export const getPostApiSessionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessions>>, TError,{data: OpenSessionCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessions>>, TError,{data: OpenSessionCommand}, TContext> => {

const mutationKey = ['postApiSessions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessions>>, {data: OpenSessionCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiSessions(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessions>>>
    export type PostApiSessionsMutationBody = OpenSessionCommand
    export type PostApiSessionsMutationError = unknown

    export const usePostApiSessions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessions>>, TError,{data: OpenSessionCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessions>>,
        TError,
        {data: OpenSessionCommand},
        TContext
      > => {
      return useMutation(getPostApiSessionsMutationOptions(options), queryClient);
    }
    export const getApiSessions = (
    params?: GetApiSessionsParams,
 signal?: AbortSignal
) => {


      return customInstance<SessionDto[]>(
      {url: `/api/Sessions`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiSessionsQueryKey = (params?: GetApiSessionsParams,) => {
    return [
    `/api/Sessions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessions>>, TError = unknown>(params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessions>>> = ({ signal }) => getApiSessions(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessions>>>
export type GetApiSessionsQueryError = unknown


export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = unknown>(
 params: undefined |  GetApiSessionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessions>>,
          TError,
          Awaited<ReturnType<typeof getApiSessions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = unknown>(
 params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessions>>,
          TError,
          Awaited<ReturnType<typeof getApiSessions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = unknown>(
 params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = unknown>(
 params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const postApiSessionsIdClose = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Sessions/${id}/close`, method: 'POST', signal
    },
      );
    }



export const getPostApiSessionsIdCloseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdClose>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdClose>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['postApiSessionsIdClose'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessionsIdClose>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  postApiSessionsIdClose(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionsIdCloseMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessionsIdClose>>>

    export type PostApiSessionsIdCloseMutationError = unknown

    export const usePostApiSessionsIdClose = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdClose>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessionsIdClose>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getPostApiSessionsIdCloseMutationOptions(options), queryClient);
    }
    export const postApiSessionsIdCancel = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Sessions/${id}/cancel`, method: 'POST', signal
    },
      );
    }



export const getPostApiSessionsIdCancelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdCancel>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdCancel>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['postApiSessionsIdCancel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessionsIdCancel>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  postApiSessionsIdCancel(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionsIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessionsIdCancel>>>

    export type PostApiSessionsIdCancelMutationError = unknown

    export const usePostApiSessionsIdCancel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdCancel>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessionsIdCancel>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getPostApiSessionsIdCancelMutationOptions(options), queryClient);
    }
    export const getApiSessionsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<SessionDto>(
      {url: `/api/Sessions/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiSessionsIdQueryKey = (id: number | string,) => {
    return [
    `/api/Sessions/${id}`
    ] as const;
    }


export const getGetApiSessionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsId>>> = ({ signal }) => getApiSessionsId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsId>>>
export type GetApiSessionsIdQueryError = unknown


export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






