/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignStaffCommand,
  CourseOfferingStaffDto,
  GetApiCourseOfferingStaffsParams
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiCourseOfferingStaffs = (
    assignStaffCommand: AssignStaffCommand,
 signal?: AbortSignal
) => {


      return customInstance<CourseOfferingStaffDto>(
      {url: `/api/CourseOfferingStaffs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignStaffCommand, signal
    },
      );
    }



export const getPostApiCourseOfferingStaffsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCourseOfferingStaffs>>, TError,{data: AssignStaffCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCourseOfferingStaffs>>, TError,{data: AssignStaffCommand}, TContext> => {

const mutationKey = ['postApiCourseOfferingStaffs'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCourseOfferingStaffs>>, {data: AssignStaffCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiCourseOfferingStaffs(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCourseOfferingStaffsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCourseOfferingStaffs>>>
    export type PostApiCourseOfferingStaffsMutationBody = AssignStaffCommand
    export type PostApiCourseOfferingStaffsMutationError = unknown

    export const usePostApiCourseOfferingStaffs = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCourseOfferingStaffs>>, TError,{data: AssignStaffCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCourseOfferingStaffs>>,
        TError,
        {data: AssignStaffCommand},
        TContext
      > => {
      return useMutation(getPostApiCourseOfferingStaffsMutationOptions(options), queryClient);
    }
    export const getApiCourseOfferingStaffs = (
    params?: GetApiCourseOfferingStaffsParams,
 signal?: AbortSignal
) => {


      return customInstance<CourseOfferingStaffDto[]>(
      {url: `/api/CourseOfferingStaffs`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiCourseOfferingStaffsQueryKey = (params?: GetApiCourseOfferingStaffsParams,) => {
    return [
    `/api/CourseOfferingStaffs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCourseOfferingStaffsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError = unknown>(params?: GetApiCourseOfferingStaffsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCourseOfferingStaffsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>> = ({ signal }) => getApiCourseOfferingStaffs(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCourseOfferingStaffsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>>
export type GetApiCourseOfferingStaffsQueryError = unknown


export function useGetApiCourseOfferingStaffs<TData = Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError = unknown>(
 params: undefined |  GetApiCourseOfferingStaffsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>,
          TError,
          Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourseOfferingStaffs<TData = Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError = unknown>(
 params?: GetApiCourseOfferingStaffsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>,
          TError,
          Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourseOfferingStaffs<TData = Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError = unknown>(
 params?: GetApiCourseOfferingStaffsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCourseOfferingStaffs<TData = Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError = unknown>(
 params?: GetApiCourseOfferingStaffsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingStaffs>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCourseOfferingStaffsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const deleteApiCourseOfferingStaffsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/CourseOfferingStaffs/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiCourseOfferingStaffsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCourseOfferingStaffsId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCourseOfferingStaffsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiCourseOfferingStaffsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCourseOfferingStaffsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCourseOfferingStaffsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCourseOfferingStaffsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCourseOfferingStaffsId>>>

    export type DeleteApiCourseOfferingStaffsIdMutationError = unknown

    export const useDeleteApiCourseOfferingStaffsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCourseOfferingStaffsId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCourseOfferingStaffsId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiCourseOfferingStaffsIdMutationOptions(options), queryClient);
    }
