/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttendanceDto,
  AttendanceMatrixResult,
  GetApiAttendancesMatrixParams,
  GetApiAttendancesOverviewParams,
  MarkAttendanceCommand,
  ScanResult,
  StudentAttendanceOverview,
  StudentScanAttendanceCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiAttendancesMark = (
    markAttendanceCommand: MarkAttendanceCommand,
 signal?: AbortSignal
) => {


      return customInstance<number | string>(
      {url: `/api/Attendances/mark`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: markAttendanceCommand, signal
    },
      );
    }



export const getPostApiAttendancesMarkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAttendancesMark>>, TError,{data: MarkAttendanceCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAttendancesMark>>, TError,{data: MarkAttendanceCommand}, TContext> => {

const mutationKey = ['postApiAttendancesMark'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAttendancesMark>>, {data: MarkAttendanceCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiAttendancesMark(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAttendancesMarkMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAttendancesMark>>>
    export type PostApiAttendancesMarkMutationBody = MarkAttendanceCommand
    export type PostApiAttendancesMarkMutationError = unknown

    export const usePostApiAttendancesMark = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAttendancesMark>>, TError,{data: MarkAttendanceCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAttendancesMark>>,
        TError,
        {data: MarkAttendanceCommand},
        TContext
      > => {
      return useMutation(getPostApiAttendancesMarkMutationOptions(options), queryClient);
    }
    export const postApiAttendancesScan = (
    studentScanAttendanceCommand: StudentScanAttendanceCommand,
 signal?: AbortSignal
) => {


      return customInstance<ScanResult>(
      {url: `/api/Attendances/scan`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: studentScanAttendanceCommand, signal
    },
      );
    }



export const getPostApiAttendancesScanMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAttendancesScan>>, TError,{data: StudentScanAttendanceCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAttendancesScan>>, TError,{data: StudentScanAttendanceCommand}, TContext> => {

const mutationKey = ['postApiAttendancesScan'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAttendancesScan>>, {data: StudentScanAttendanceCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiAttendancesScan(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAttendancesScanMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAttendancesScan>>>
    export type PostApiAttendancesScanMutationBody = StudentScanAttendanceCommand
    export type PostApiAttendancesScanMutationError = unknown

    export const usePostApiAttendancesScan = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAttendancesScan>>, TError,{data: StudentScanAttendanceCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAttendancesScan>>,
        TError,
        {data: StudentScanAttendanceCommand},
        TContext
      > => {
      return useMutation(getPostApiAttendancesScanMutationOptions(options), queryClient);
    }
    export const getApiAttendancesSessionSessionId = (
    sessionId: number | string,
 signal?: AbortSignal
) => {


      return customInstance<AttendanceDto[]>(
      {url: `/api/Attendances/session/${sessionId}`, method: 'GET', signal
    },
      );
    }




export const getGetApiAttendancesSessionSessionIdQueryKey = (sessionId: number | string,) => {
    return [
    `/api/Attendances/session/${sessionId}`
    ] as const;
    }


export const getGetApiAttendancesSessionSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError = unknown>(sessionId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAttendancesSessionSessionIdQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>> = ({ signal }) => getApiAttendancesSessionSessionId(sessionId, signal);





   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAttendancesSessionSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>>
export type GetApiAttendancesSessionSessionIdQueryError = unknown


export function useGetApiAttendancesSessionSessionId<TData = Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError = unknown>(
 sessionId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesSessionSessionId<TData = Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError = unknown>(
 sessionId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesSessionSessionId<TData = Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError = unknown>(
 sessionId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAttendancesSessionSessionId<TData = Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError = unknown>(
 sessionId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesSessionSessionId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAttendancesSessionSessionIdQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiAttendancesOverview = (
    params?: GetApiAttendancesOverviewParams,
 signal?: AbortSignal
) => {


      return customInstance<StudentAttendanceOverview>(
      {url: `/api/Attendances/overview`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiAttendancesOverviewQueryKey = (params?: GetApiAttendancesOverviewParams,) => {
    return [
    `/api/Attendances/overview`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAttendancesOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError = unknown>(params?: GetApiAttendancesOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAttendancesOverviewQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAttendancesOverview>>> = ({ signal }) => getApiAttendancesOverview(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAttendancesOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAttendancesOverview>>>
export type GetApiAttendancesOverviewQueryError = unknown


export function useGetApiAttendancesOverview<TData = Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError = unknown>(
 params: undefined |  GetApiAttendancesOverviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesOverview>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesOverview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesOverview<TData = Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError = unknown>(
 params?: GetApiAttendancesOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesOverview>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesOverview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesOverview<TData = Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError = unknown>(
 params?: GetApiAttendancesOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAttendancesOverview<TData = Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError = unknown>(
 params?: GetApiAttendancesOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesOverview>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAttendancesOverviewQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiAttendancesMatrix = (
    params?: GetApiAttendancesMatrixParams,
 signal?: AbortSignal
) => {


      return customInstance<AttendanceMatrixResult>(
      {url: `/api/Attendances/matrix`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiAttendancesMatrixQueryKey = (params?: GetApiAttendancesMatrixParams,) => {
    return [
    `/api/Attendances/matrix`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAttendancesMatrixQueryOptions = <TData = Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError = unknown>(params?: GetApiAttendancesMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAttendancesMatrixQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAttendancesMatrix>>> = ({ signal }) => getApiAttendancesMatrix(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAttendancesMatrixQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAttendancesMatrix>>>
export type GetApiAttendancesMatrixQueryError = unknown


export function useGetApiAttendancesMatrix<TData = Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError = unknown>(
 params: undefined |  GetApiAttendancesMatrixParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesMatrix>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesMatrix>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesMatrix<TData = Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError = unknown>(
 params?: GetApiAttendancesMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesMatrix>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesMatrix>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesMatrix<TData = Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError = unknown>(
 params?: GetApiAttendancesMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAttendancesMatrix<TData = Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError = unknown>(
 params?: GetApiAttendancesMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesMatrix>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAttendancesMatrixQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiAttendancesId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<AttendanceDto>(
      {url: `/api/Attendances/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiAttendancesIdQueryKey = (id: number | string,) => {
    return [
    `/api/Attendances/${id}`
    ] as const;
    }


export const getGetApiAttendancesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAttendancesId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAttendancesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAttendancesId>>> = ({ signal }) => getApiAttendancesId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAttendancesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAttendancesId>>>
export type GetApiAttendancesIdQueryError = unknown


export function useGetApiAttendancesId<TData = Awaited<ReturnType<typeof getApiAttendancesId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesId>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesId<TData = Awaited<ReturnType<typeof getApiAttendancesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAttendancesId>>,
          TError,
          Awaited<ReturnType<typeof getApiAttendancesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAttendancesId<TData = Awaited<ReturnType<typeof getApiAttendancesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAttendancesId<TData = Awaited<ReturnType<typeof getApiAttendancesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAttendancesId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAttendancesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






