/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTermCommand,
  TermDto,
  UpdateTermCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiTerms = (
    createTermCommand: CreateTermCommand,
 signal?: AbortSignal
) => {


      return customInstance<number | string>(
      {url: `/api/Terms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTermCommand, signal
    },
      );
    }



export const getPostApiTermsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTerms>>, TError,{data: CreateTermCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiTerms>>, TError,{data: CreateTermCommand}, TContext> => {

const mutationKey = ['postApiTerms'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTerms>>, {data: CreateTermCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiTerms(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTermsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTerms>>>
    export type PostApiTermsMutationBody = CreateTermCommand
    export type PostApiTermsMutationError = unknown

    export const usePostApiTerms = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTerms>>, TError,{data: CreateTermCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTerms>>,
        TError,
        {data: CreateTermCommand},
        TContext
      > => {
      return useMutation(getPostApiTermsMutationOptions(options), queryClient);
    }
    export const getApiTerms = (

 signal?: AbortSignal
) => {


      return customInstance<TermDto[]>(
      {url: `/api/Terms`, method: 'GET', signal
    },
      );
    }




export const getGetApiTermsQueryKey = () => {
    return [
    `/api/Terms`
    ] as const;
    }


export const getGetApiTermsQueryOptions = <TData = Awaited<ReturnType<typeof getApiTerms>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTerms>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTermsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTerms>>> = ({ signal }) => getApiTerms(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTerms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTermsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTerms>>>
export type GetApiTermsQueryError = unknown


export function useGetApiTerms<TData = Awaited<ReturnType<typeof getApiTerms>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTerms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTerms>>,
          TError,
          Awaited<ReturnType<typeof getApiTerms>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTerms<TData = Awaited<ReturnType<typeof getApiTerms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTerms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTerms>>,
          TError,
          Awaited<ReturnType<typeof getApiTerms>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTerms<TData = Awaited<ReturnType<typeof getApiTerms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTerms>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTerms<TData = Awaited<ReturnType<typeof getApiTerms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTerms>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTermsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const putApiTermsId = (
    id: number | string,
    updateTermCommand: UpdateTermCommand,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Terms/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTermCommand, signal
    },
      );
    }



export const getPutApiTermsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTermsId>>, TError,{id: number | string;data: UpdateTermCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiTermsId>>, TError,{id: number | string;data: UpdateTermCommand}, TContext> => {

const mutationKey = ['putApiTermsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiTermsId>>, {id: number | string;data: UpdateTermCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiTermsId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiTermsId>>>
    export type PutApiTermsIdMutationBody = UpdateTermCommand
    export type PutApiTermsIdMutationError = unknown

    export const usePutApiTermsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTermsId>>, TError,{id: number | string;data: UpdateTermCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiTermsId>>,
        TError,
        {id: number | string;data: UpdateTermCommand},
        TContext
      > => {
      return useMutation(getPutApiTermsIdMutationOptions(options), queryClient);
    }
    export const deleteApiTermsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Terms/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiTermsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTermsId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTermsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiTermsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTermsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiTermsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTermsId>>>

    export type DeleteApiTermsIdMutationError = unknown

    export const useDeleteApiTermsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTermsId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiTermsId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiTermsIdMutationOptions(options), queryClient);
    }
    export const getApiTermsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<TermDto>(
      {url: `/api/Terms/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiTermsIdQueryKey = (id: number | string,) => {
    return [
    `/api/Terms/${id}`
    ] as const;
    }


export const getGetApiTermsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiTermsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTermsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTermsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTermsId>>> = ({ signal }) => getApiTermsId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTermsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTermsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTermsId>>>
export type GetApiTermsIdQueryError = unknown


export function useGetApiTermsId<TData = Awaited<ReturnType<typeof getApiTermsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTermsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTermsId>>,
          TError,
          Awaited<ReturnType<typeof getApiTermsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTermsId<TData = Awaited<ReturnType<typeof getApiTermsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTermsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTermsId>>,
          TError,
          Awaited<ReturnType<typeof getApiTermsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTermsId<TData = Awaited<ReturnType<typeof getApiTermsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTermsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTermsId<TData = Awaited<ReturnType<typeof getApiTermsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTermsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTermsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






