/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateModuleCommand,
  GetApiModulesParams,
  ModuleDto,
  UpdateModuleCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiModules = (
    createModuleCommand: CreateModuleCommand,
 signal?: AbortSignal
) => {


      return customInstance<number | string>(
      {url: `/api/Modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createModuleCommand, signal
    },
      );
    }



export const getPostApiModulesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiModules>>, TError,{data: CreateModuleCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiModules>>, TError,{data: CreateModuleCommand}, TContext> => {

const mutationKey = ['postApiModules'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiModules>>, {data: CreateModuleCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiModules(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiModulesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiModules>>>
    export type PostApiModulesMutationBody = CreateModuleCommand
    export type PostApiModulesMutationError = unknown

    export const usePostApiModules = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiModules>>, TError,{data: CreateModuleCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiModules>>,
        TError,
        {data: CreateModuleCommand},
        TContext
      > => {
      return useMutation(getPostApiModulesMutationOptions(options), queryClient);
    }
    export const getApiModules = (
    params?: GetApiModulesParams,
 signal?: AbortSignal
) => {


      return customInstance<ModuleDto[]>(
      {url: `/api/Modules`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiModulesQueryKey = (params?: GetApiModulesParams,) => {
    return [
    `/api/Modules`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiModulesQueryOptions = <TData = Awaited<ReturnType<typeof getApiModules>>, TError = unknown>(params?: GetApiModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModules>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiModulesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiModules>>> = ({ signal }) => getApiModules(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiModules>>>
export type GetApiModulesQueryError = unknown


export function useGetApiModules<TData = Awaited<ReturnType<typeof getApiModules>>, TError = unknown>(
 params: undefined |  GetApiModulesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModules>>,
          TError,
          Awaited<ReturnType<typeof getApiModules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModules<TData = Awaited<ReturnType<typeof getApiModules>>, TError = unknown>(
 params?: GetApiModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModules>>,
          TError,
          Awaited<ReturnType<typeof getApiModules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModules<TData = Awaited<ReturnType<typeof getApiModules>>, TError = unknown>(
 params?: GetApiModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModules>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiModules<TData = Awaited<ReturnType<typeof getApiModules>>, TError = unknown>(
 params?: GetApiModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModules>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiModulesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const putApiModulesId = (
    id: number | string,
    updateModuleCommand: UpdateModuleCommand,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Modules/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateModuleCommand, signal
    },
      );
    }



export const getPutApiModulesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiModulesId>>, TError,{id: number | string;data: UpdateModuleCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiModulesId>>, TError,{id: number | string;data: UpdateModuleCommand}, TContext> => {

const mutationKey = ['putApiModulesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiModulesId>>, {id: number | string;data: UpdateModuleCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiModulesId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiModulesId>>>
    export type PutApiModulesIdMutationBody = UpdateModuleCommand
    export type PutApiModulesIdMutationError = unknown

    export const usePutApiModulesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiModulesId>>, TError,{id: number | string;data: UpdateModuleCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiModulesId>>,
        TError,
        {id: number | string;data: UpdateModuleCommand},
        TContext
      > => {
      return useMutation(getPutApiModulesIdMutationOptions(options), queryClient);
    }
    export const deleteApiModulesId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Modules/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiModulesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiModulesId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiModulesId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiModulesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiModulesId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiModulesId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiModulesId>>>

    export type DeleteApiModulesIdMutationError = unknown

    export const useDeleteApiModulesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiModulesId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiModulesId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiModulesIdMutationOptions(options), queryClient);
    }
    export const getApiModulesId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<ModuleDto>(
      {url: `/api/Modules/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiModulesIdQueryKey = (id: number | string,) => {
    return [
    `/api/Modules/${id}`
    ] as const;
    }


export const getGetApiModulesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiModulesId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModulesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiModulesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiModulesId>>> = ({ signal }) => getApiModulesId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiModulesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiModulesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiModulesId>>>
export type GetApiModulesIdQueryError = unknown


export function useGetApiModulesId<TData = Awaited<ReturnType<typeof getApiModulesId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModulesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModulesId>>,
          TError,
          Awaited<ReturnType<typeof getApiModulesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModulesId<TData = Awaited<ReturnType<typeof getApiModulesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModulesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModulesId>>,
          TError,
          Awaited<ReturnType<typeof getApiModulesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModulesId<TData = Awaited<ReturnType<typeof getApiModulesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModulesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiModulesId<TData = Awaited<ReturnType<typeof getApiModulesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModulesId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiModulesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






