/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthTokenResponse,
  DevRoleRequest,
  RefreshTokenRequest,
  RegisterCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiAuthExchange = (

 signal?: AbortSignal
) => {


      return customInstance<AuthTokenResponse>(
      {url: `/api/Auth/exchange`, method: 'POST', signal
    },
      );
    }



export const getPostApiAuthExchangeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthExchange>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthExchange>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthExchange'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthExchange>>, void> = () => {


          return  postApiAuthExchange()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthExchangeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthExchange>>>

    export type PostApiAuthExchangeMutationError = unknown

    export const usePostApiAuthExchange = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthExchange>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthExchange>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAuthExchangeMutationOptions(options), queryClient);
    }
    export const postApiAuthRefresh = (
    refreshTokenRequest: RefreshTokenRequest,
 signal?: AbortSignal
) => {


      return customInstance<AuthTokenResponse>(
      {url: `/api/Auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
      );
    }



export const getPostApiAuthRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshTokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshTokenRequest}, TContext> => {

const mutationKey = ['postApiAuthRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefresh>>, {data: RefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRefresh(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefresh>>>
    export type PostApiAuthRefreshMutationBody = RefreshTokenRequest
    export type PostApiAuthRefreshMutationError = unknown

    export const usePostApiAuthRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: RefreshTokenRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        {data: RefreshTokenRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthRefreshMutationOptions(options), queryClient);
    }
    export const postApiAuthDevRole = (
    devRoleRequest: DevRoleRequest,
 signal?: AbortSignal
) => {


      return customInstance<AuthTokenResponse>(
      {url: `/api/Auth/dev-role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: devRoleRequest, signal
    },
      );
    }



export const getPostApiAuthDevRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthDevRole>>, TError,{data: DevRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthDevRole>>, TError,{data: DevRoleRequest}, TContext> => {

const mutationKey = ['postApiAuthDevRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthDevRole>>, {data: DevRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthDevRole(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthDevRoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthDevRole>>>
    export type PostApiAuthDevRoleMutationBody = DevRoleRequest
    export type PostApiAuthDevRoleMutationError = unknown

    export const usePostApiAuthDevRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthDevRole>>, TError,{data: DevRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthDevRole>>,
        TError,
        {data: DevRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthDevRoleMutationOptions(options), queryClient);
    }
    export const postApiAuthRegister = (
    registerCommand: RegisterCommand,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerCommand, signal
    },
      );
    }



export const getPostApiAuthRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterCommand}, TContext> => {

const mutationKey = ['postApiAuthRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, {data: RegisterCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegister(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
    export type PostApiAuthRegisterMutationBody = RegisterCommand
    export type PostApiAuthRegisterMutationError = unknown

    export const usePostApiAuthRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: RegisterCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRegister>>,
        TError,
        {data: RegisterCommand},
        TContext
      > => {
      return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient);
    }
