/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseOfferingDto,
  CreateCourseOfferingCommand,
  UpdateCourseOfferingCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiCourseOfferings = (
    createCourseOfferingCommand: CreateCourseOfferingCommand,
 signal?: AbortSignal
) => {


      return customInstance<CourseOfferingDto>(
      {url: `/api/CourseOfferings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCourseOfferingCommand, signal
    },
      );
    }



export const getPostApiCourseOfferingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCourseOfferings>>, TError,{data: CreateCourseOfferingCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCourseOfferings>>, TError,{data: CreateCourseOfferingCommand}, TContext> => {

const mutationKey = ['postApiCourseOfferings'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCourseOfferings>>, {data: CreateCourseOfferingCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiCourseOfferings(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCourseOfferingsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCourseOfferings>>>
    export type PostApiCourseOfferingsMutationBody = CreateCourseOfferingCommand
    export type PostApiCourseOfferingsMutationError = unknown

    export const usePostApiCourseOfferings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCourseOfferings>>, TError,{data: CreateCourseOfferingCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCourseOfferings>>,
        TError,
        {data: CreateCourseOfferingCommand},
        TContext
      > => {
      return useMutation(getPostApiCourseOfferingsMutationOptions(options), queryClient);
    }
    export const getApiCourseOfferings = (

 signal?: AbortSignal
) => {


      return customInstance<CourseOfferingDto[]>(
      {url: `/api/CourseOfferings`, method: 'GET', signal
    },
      );
    }




export const getGetApiCourseOfferingsQueryKey = () => {
    return [
    `/api/CourseOfferings`
    ] as const;
    }


export const getGetApiCourseOfferingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCourseOfferings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCourseOfferingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCourseOfferings>>> = ({ signal }) => getApiCourseOfferings(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCourseOfferingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCourseOfferings>>>
export type GetApiCourseOfferingsQueryError = unknown


export function useGetApiCourseOfferings<TData = Awaited<ReturnType<typeof getApiCourseOfferings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourseOfferings>>,
          TError,
          Awaited<ReturnType<typeof getApiCourseOfferings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourseOfferings<TData = Awaited<ReturnType<typeof getApiCourseOfferings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourseOfferings>>,
          TError,
          Awaited<ReturnType<typeof getApiCourseOfferings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourseOfferings<TData = Awaited<ReturnType<typeof getApiCourseOfferings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCourseOfferings<TData = Awaited<ReturnType<typeof getApiCourseOfferings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferings>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCourseOfferingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const putApiCourseOfferingsId = (
    id: number | string,
    updateCourseOfferingCommand: UpdateCourseOfferingCommand,
 signal?: AbortSignal
) => {


      return customInstance<CourseOfferingDto>(
      {url: `/api/CourseOfferings/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCourseOfferingCommand, signal
    },
      );
    }



export const getPutApiCourseOfferingsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCourseOfferingsId>>, TError,{id: number | string;data: UpdateCourseOfferingCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiCourseOfferingsId>>, TError,{id: number | string;data: UpdateCourseOfferingCommand}, TContext> => {

const mutationKey = ['putApiCourseOfferingsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCourseOfferingsId>>, {id: number | string;data: UpdateCourseOfferingCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCourseOfferingsId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiCourseOfferingsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCourseOfferingsId>>>
    export type PutApiCourseOfferingsIdMutationBody = UpdateCourseOfferingCommand
    export type PutApiCourseOfferingsIdMutationError = unknown

    export const usePutApiCourseOfferingsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCourseOfferingsId>>, TError,{id: number | string;data: UpdateCourseOfferingCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCourseOfferingsId>>,
        TError,
        {id: number | string;data: UpdateCourseOfferingCommand},
        TContext
      > => {
      return useMutation(getPutApiCourseOfferingsIdMutationOptions(options), queryClient);
    }
    export const deleteApiCourseOfferingsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/CourseOfferings/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiCourseOfferingsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCourseOfferingsId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCourseOfferingsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiCourseOfferingsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCourseOfferingsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCourseOfferingsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCourseOfferingsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCourseOfferingsId>>>

    export type DeleteApiCourseOfferingsIdMutationError = unknown

    export const useDeleteApiCourseOfferingsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCourseOfferingsId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCourseOfferingsId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiCourseOfferingsIdMutationOptions(options), queryClient);
    }
    export const getApiCourseOfferingsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<CourseOfferingDto>(
      {url: `/api/CourseOfferings/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiCourseOfferingsIdQueryKey = (id: number | string,) => {
    return [
    `/api/CourseOfferings/${id}`
    ] as const;
    }


export const getGetApiCourseOfferingsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCourseOfferingsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCourseOfferingsId>>> = ({ signal }) => getApiCourseOfferingsId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCourseOfferingsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCourseOfferingsId>>>
export type GetApiCourseOfferingsIdQueryError = unknown


export function useGetApiCourseOfferingsId<TData = Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourseOfferingsId>>,
          TError,
          Awaited<ReturnType<typeof getApiCourseOfferingsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourseOfferingsId<TData = Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourseOfferingsId>>,
          TError,
          Awaited<ReturnType<typeof getApiCourseOfferingsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourseOfferingsId<TData = Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCourseOfferingsId<TData = Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourseOfferingsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCourseOfferingsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






