/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseDto,
  CreateCourseCommand,
  UpdateCourseCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiCourses = (
    createCourseCommand: CreateCourseCommand,
 signal?: AbortSignal
) => {


      return customInstance<CourseDto>(
      {url: `/api/Courses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCourseCommand, signal
    },
      );
    }



export const getPostApiCoursesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCourses>>, TError,{data: CreateCourseCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCourses>>, TError,{data: CreateCourseCommand}, TContext> => {

const mutationKey = ['postApiCourses'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCourses>>, {data: CreateCourseCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiCourses(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCoursesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCourses>>>
    export type PostApiCoursesMutationBody = CreateCourseCommand
    export type PostApiCoursesMutationError = unknown

    export const usePostApiCourses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCourses>>, TError,{data: CreateCourseCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCourses>>,
        TError,
        {data: CreateCourseCommand},
        TContext
      > => {
      return useMutation(getPostApiCoursesMutationOptions(options), queryClient);
    }
    export const getApiCourses = (

 signal?: AbortSignal
) => {


      return customInstance<CourseDto[]>(
      {url: `/api/Courses`, method: 'GET', signal
    },
      );
    }




export const getGetApiCoursesQueryKey = () => {
    return [
    `/api/Courses`
    ] as const;
    }


export const getGetApiCoursesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCourses>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCoursesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCourses>>> = ({ signal }) => getApiCourses(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCourses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCourses>>>
export type GetApiCoursesQueryError = unknown


export function useGetApiCourses<TData = Awaited<ReturnType<typeof getApiCourses>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourses>>,
          TError,
          Awaited<ReturnType<typeof getApiCourses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourses<TData = Awaited<ReturnType<typeof getApiCourses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCourses>>,
          TError,
          Awaited<ReturnType<typeof getApiCourses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCourses<TData = Awaited<ReturnType<typeof getApiCourses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCourses<TData = Awaited<ReturnType<typeof getApiCourses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCourses>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCoursesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const putApiCoursesId = (
    id: number | string,
    updateCourseCommand: UpdateCourseCommand,
 signal?: AbortSignal
) => {


      return customInstance<CourseDto>(
      {url: `/api/Courses/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCourseCommand, signal
    },
      );
    }



export const getPutApiCoursesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCoursesId>>, TError,{id: number | string;data: UpdateCourseCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiCoursesId>>, TError,{id: number | string;data: UpdateCourseCommand}, TContext> => {

const mutationKey = ['putApiCoursesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCoursesId>>, {id: number | string;data: UpdateCourseCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCoursesId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiCoursesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCoursesId>>>
    export type PutApiCoursesIdMutationBody = UpdateCourseCommand
    export type PutApiCoursesIdMutationError = unknown

    export const usePutApiCoursesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCoursesId>>, TError,{id: number | string;data: UpdateCourseCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCoursesId>>,
        TError,
        {id: number | string;data: UpdateCourseCommand},
        TContext
      > => {
      return useMutation(getPutApiCoursesIdMutationOptions(options), queryClient);
    }
    export const deleteApiCoursesId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Courses/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiCoursesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCoursesId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCoursesId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiCoursesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCoursesId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCoursesId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCoursesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCoursesId>>>

    export type DeleteApiCoursesIdMutationError = unknown

    export const useDeleteApiCoursesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCoursesId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCoursesId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiCoursesIdMutationOptions(options), queryClient);
    }
    export const getApiCoursesId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<CourseDto>(
      {url: `/api/Courses/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiCoursesIdQueryKey = (id: number | string,) => {
    return [
    `/api/Courses/${id}`
    ] as const;
    }


export const getGetApiCoursesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCoursesId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCoursesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCoursesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCoursesId>>> = ({ signal }) => getApiCoursesId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCoursesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCoursesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCoursesId>>>
export type GetApiCoursesIdQueryError = unknown


export function useGetApiCoursesId<TData = Awaited<ReturnType<typeof getApiCoursesId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCoursesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCoursesId>>,
          TError,
          Awaited<ReturnType<typeof getApiCoursesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCoursesId<TData = Awaited<ReturnType<typeof getApiCoursesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCoursesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCoursesId>>,
          TError,
          Awaited<ReturnType<typeof getApiCoursesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCoursesId<TData = Awaited<ReturnType<typeof getApiCoursesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCoursesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCoursesId<TData = Awaited<ReturnType<typeof getApiCoursesId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCoursesId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCoursesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






