/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceMethod } from './attendanceMethod';
import type { AttendanceStatus } from './attendanceStatus';

export interface AttendanceDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId: number | string;
  userName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sessionId: number | string;
  moduleTitle: string;
  status: AttendanceStatus;
  method: AttendanceMethod;
  /** @nullable */
  recordedAt: string | null;
  createdAt: string;
}
