/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface BulkEnrollStudentItem {
  studentNumber: string;
  /** @nullable */
  importedName: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sectionId: number | string;
}
