/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrollStudentResult } from './bulkEnrollStudentResult';

export interface BulkEnrollStudentsResult {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  successCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  errorCount: number | string;
  results: BulkEnrollStudentResult[];
}
