/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrollStudentItem } from './bulkEnrollStudentItem';

export interface BulkEnrollStudentsCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  courseOfferingId: number | string;
  students: BulkEnrollStudentItem[];
}
