/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCourseCommand {
  code: string;
  title: string;
  /** @nullable */
  description: string | null;
}
