/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTermCommand {
  code: string;
  startDate: string;
  endDate: string;
}
