/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceMethod } from './attendanceMethod';
import type { AttendanceStatus } from './attendanceStatus';

export interface MarkAttendanceCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sessionId: number | string;
  status: AttendanceStatus;
  method: AttendanceMethod;
}
