/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MyEnrollmentDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId: number | string;
  userName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  courseOfferingId: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  courseId: number | string;
  courseCode: string;
  courseTitle: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  termId: number | string;
  termCode: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sectionId: number | string;
  sectionName: string;
  createdAt: string;
}
