/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceMethod } from './attendanceMethod';

export interface OpenSessionCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  moduleId: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  sectionId: number | string | null;
  selectedMethod: AttendanceMethod;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  openedByUserId: number | string;
}
