/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface RegisterCommand {
  name: string;
  email: string;
  password: string;
  role: UserRole;
}
