/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterResult {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId: number | string;
  succeeded: boolean;
  errors: string[];
}
