/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceMethod } from './attendanceMethod';
import type { SessionStatus } from './sessionStatus';

export interface ScanPreviewDto {
  courseCode: string;
  courseTitle: string;
  moduleTitle: string;
  /** @nullable */
  sectionName: string | null;
  openedByUserName: string;
  openedAt: string;
  status: SessionStatus;
  selectedMethod: AttendanceMethod;
  canSign: boolean;
  alreadyRecorded: boolean;
  message: string;
}
