/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ScanResult {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  attendanceId: number | string;
  sectionSwitched: boolean;
  alreadyRecorded: boolean;
  success: boolean;
  message: string;
}
