/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceMethod } from './attendanceMethod';
import type { SessionStatus } from './sessionStatus';

export interface SessionDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  moduleId: number | string;
  moduleTitle: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  sectionId: number | string | null;
  /** @nullable */
  sectionName: string | null;
  status: SessionStatus;
  selectedMethod: AttendanceMethod;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  openedByUserId: number | string;
  openedByUserName: string;
  openedAt: string;
  /** @nullable */
  closedAt: string | null;
  createdAt: string;
}
