/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceMethod } from './attendanceMethod';

export interface StudentScanAttendanceCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sessionId: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  studentUserId: number | string;
  method: AttendanceMethod;
}
