/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface StudentRow {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  studentId: number | string;
  studentName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  currentSectionId: number | string;
  currentSectionName: string;
  attendanceStatuses: string[];
}
