/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCourseOfferingCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @nullable */
  note: string | null;
}
