/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  Student: 'Student',
  Staff: 'Staff',
  Admin: 'Admin',
} as const;
