/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSectionCommand,
  GetApiSectionsParams,
  SectionDto,
  UpdateSectionCommand
} from '../model';

import { customInstance } from '../../axios-instance';




export const postApiSections = (
    createSectionCommand: CreateSectionCommand,
 signal?: AbortSignal
) => {


      return customInstance<number | string>(
      {url: `/api/Sections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSectionCommand, signal
    },
      );
    }



export const getPostApiSectionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSections>>, TError,{data: CreateSectionCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSections>>, TError,{data: CreateSectionCommand}, TContext> => {

const mutationKey = ['postApiSections'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSections>>, {data: CreateSectionCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiSections(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSectionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSections>>>
    export type PostApiSectionsMutationBody = CreateSectionCommand
    export type PostApiSectionsMutationError = unknown

    export const usePostApiSections = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSections>>, TError,{data: CreateSectionCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSections>>,
        TError,
        {data: CreateSectionCommand},
        TContext
      > => {
      return useMutation(getPostApiSectionsMutationOptions(options), queryClient);
    }
    export const getApiSections = (
    params?: GetApiSectionsParams,
 signal?: AbortSignal
) => {


      return customInstance<SectionDto[]>(
      {url: `/api/Sections`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiSectionsQueryKey = (params?: GetApiSectionsParams,) => {
    return [
    `/api/Sections`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiSectionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSections>>, TError = unknown>(params?: GetApiSectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSections>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSectionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSections>>> = ({ signal }) => getApiSections(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSectionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSections>>>
export type GetApiSectionsQueryError = unknown


export function useGetApiSections<TData = Awaited<ReturnType<typeof getApiSections>>, TError = unknown>(
 params: undefined |  GetApiSectionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSections>>,
          TError,
          Awaited<ReturnType<typeof getApiSections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSections<TData = Awaited<ReturnType<typeof getApiSections>>, TError = unknown>(
 params?: GetApiSectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSections>>,
          TError,
          Awaited<ReturnType<typeof getApiSections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSections<TData = Awaited<ReturnType<typeof getApiSections>>, TError = unknown>(
 params?: GetApiSectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSections>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSections<TData = Awaited<ReturnType<typeof getApiSections>>, TError = unknown>(
 params?: GetApiSectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSections>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSectionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const putApiSectionsId = (
    id: number | string,
    updateSectionCommand: UpdateSectionCommand,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Sections/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSectionCommand, signal
    },
      );
    }



export const getPutApiSectionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSectionsId>>, TError,{id: number | string;data: UpdateSectionCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiSectionsId>>, TError,{id: number | string;data: UpdateSectionCommand}, TContext> => {

const mutationKey = ['putApiSectionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiSectionsId>>, {id: number | string;data: UpdateSectionCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiSectionsId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiSectionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiSectionsId>>>
    export type PutApiSectionsIdMutationBody = UpdateSectionCommand
    export type PutApiSectionsIdMutationError = unknown

    export const usePutApiSectionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSectionsId>>, TError,{id: number | string;data: UpdateSectionCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiSectionsId>>,
        TError,
        {id: number | string;data: UpdateSectionCommand},
        TContext
      > => {
      return useMutation(getPutApiSectionsIdMutationOptions(options), queryClient);
    }
    export const deleteApiSectionsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Sections/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiSectionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiSectionsId>>, TError,{id: number | string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiSectionsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiSectionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiSectionsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiSectionsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiSectionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiSectionsId>>>

    export type DeleteApiSectionsIdMutationError = unknown

    export const useDeleteApiSectionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiSectionsId>>, TError,{id: number | string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiSectionsId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiSectionsIdMutationOptions(options), queryClient);
    }
    export const getApiSectionsId = (
    id: number | string,
 signal?: AbortSignal
) => {


      return customInstance<SectionDto>(
      {url: `/api/Sections/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiSectionsIdQueryKey = (id: number | string,) => {
    return [
    `/api/Sections/${id}`
    ] as const;
    }


export const getGetApiSectionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiSectionsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSectionsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSectionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSectionsId>>> = ({ signal }) => getApiSectionsId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSectionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSectionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSectionsId>>>
export type GetApiSectionsIdQueryError = unknown


export function useGetApiSectionsId<TData = Awaited<ReturnType<typeof getApiSectionsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSectionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSectionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSectionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSectionsId<TData = Awaited<ReturnType<typeof getApiSectionsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSectionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSectionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSectionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSectionsId<TData = Awaited<ReturnType<typeof getApiSectionsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSectionsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSectionsId<TData = Awaited<ReturnType<typeof getApiSectionsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSectionsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSectionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






